name: alarm
description: A simple Flutter alarm manager plugin for both iOS and Android.
version: 1.2.2
homepage: https://github.com/gdelataillade/alarm

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  android_alarm_manager_plus: 3.0.2
  flutter:
    sdk: flutter
  flutter_fgbg: ^0.3.0
  flutter_local_notifications: 15.1.1
  just_audio: ^0.9.34
  plugin_platform_interface: ^2.1.4
  shared_preferences: ^2.1.2
  timezone: ^0.9.2
  vibration: ^1.8.1
  volume_controller: ^2.0.7
  freezed_annotation: 2.2.0
  json_annotation: 4.8.1
  rxdart: 0.27.7
  permission_handler: 11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: 2.3.2
  json_serializable: 6.7.1
  build_runner: 2.4.5

flutter:
  assets:
    - assets/blank.mp3
  plugin:
    platforms:
      android:
        package: com.gdelataillade.alarm.alarm
        pluginClass: AlarmPlugin
      ios:
        pluginClass: AlarmPlugin
