name: alarm
description: A simple Flutter alarm manager plugin for both iOS and Android.
version: 2.0.0
homepage: https://github.com/gdelataillade/alarm

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: 0.9.36
  permission_handler: 11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  assets:
    - assets/blank.mp3
  plugin:
    platforms:
      android:
        package: com.gdelataillade.alarm.alarm
        pluginClass: AlarmPlugin
      ios:
        pluginClass: AlarmPlugin
